version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - '5436:5432'
  monkedb:
    image: 'mongo:4.4.6'
    container_name: 'monke'
    ports:
      - '27017:27017'
  redis:
    image: redis
    ports:
      - '6373:6373'
