version: '3'

volumes:
  prometheus_data: {}
  grafana_data: {}


services:
#  postgres:
#    image: postgres
#    environment:
#      POSTGRES_PASSWORD: 'qwerty'
#    ports:
#      - '5436:5436'
  monkedb:
    image: 'mongo:4.4.6'
    container_name: 'monke'
    ports:
      - '27017:27017'
  redis:
    image: redis
    ports:
      - '6379:6379'
#  migrate:
#    image: migrate/migrate
#    volumes:
#      - /schema:/schema
##    command: ["-path", "/schema", "-database", "postgres://postgres:qwerty@postgres:5432/postgres?sslmode=disable", "up", "3"]
#    command: ["-path", "./schema", "-database", "postgres://postgres:qwerty@postgres:5432/postgres?sslmode=disable", "up"]
#    depends_on:
#      - postgres
##  prometheus:
#    image: prom/prometheus:latest
#    volumes:
#      - /etc/prometheus:/etc/prometheus
##    command:
##      - '--config.file=/etc/prometheus/prometheus.yml'
##      - '--storage.tsdb.path=/prometheus'
#    ports:
#      - '9090:9090'
#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    depends_on:
#      - prometheus
#  taxi:
#    build: .