name: Code checks

on:
  push:
    branches: [auth]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-golang@v2
        with:
        go-version: 1.18
      - name: linter
        run: golangci-lint run ./...
