name: Code checks

on:
  push:
    branches: [auth]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: test project
        run : |
          go test -v ./...

      - name: Run linter
        run: golangci-lint run ./...
      - name: Run tests
        run: go test ./...

